### PR TITLE
Add TransformerVC implementation

### PR DESCRIPTION
**Pull request by ArkhamImp**
The code has been tested, and the model is under training.

### CODE REVIEW

**Comment by lmxue** [comment]
Thanks for your efforts. There are some suggestions for a standard PR, especially for the PR that integrates a new model into Amphion:
- Please format the code using `black` 
- Please detail PR descriptions, including the PR purpose, supported model, etc.
- Please attach the pre-trained models as well as some samples in this PR.

**Comment by lmxue** [comment]
Thanks for your efforts. There are some suggestions for a standard PR, especially for the PR that integrates a new model into Amphion:
- Please format the code using `black` 
- Please detail PR descriptions, including the PR purpose, supported model, etc.
- Please attach the pre-trained models as well as some samples in this PR.

**Comment by RMSnow** [comment]
Thanks @ArkhamImp a lot to integrate our first VC model. For the "New Feature" PR, the review stage is more strict and usually takes several request-change loops. 

You can follow these two PRs to provide the inference samples of TransformerVC, so that we can ensure the code is bug-free:
1. https://github.com/open-mmlab/Amphion/pull/56
2. https://github.com/open-mmlab/Amphion/pull/14

A perfect "New Feature" PR will contain: 
- (1) Code; 
- (2) Generated Samples; 
- (3) Recipe and Doc; 
- (4) Pretrained Models in our Huggingface; 
- (5) Gradio Demo in our Huggingface. 

I think for this PR, you need to provide (1)-(2) at least. Besides, you can schedule an expected date for (3) to inform others. After (1)-(3), we can assign other developers to cooperate with you to accomplish (4) and (5).

**Comment by ArkhamImp** [comment]
# Voice Conversion Samples
## Sample 1
### Source
https://github.com/open-mmlab/Amphion/assets/16316402/f2f771c9-df52-481b-9750-f61b0c9d7ac7
### Target
https://github.com/open-mmlab/Amphion/assets/16316402/78776ff3-d469-4813-bab2-a3dc3b48e1d9
### Converted
https://github.com/open-mmlab/Amphion/assets/16316402/2fc2d40c-a1e3-43b3-a302-7acbe8993732
## Sample 2
### Source
https://github.com/open-mmlab/Amphion/assets/16316402/ff82282b-5f90-4f37-9050-994c1bc411c9
### Target
https://github.com/open-mmlab/Amphion/assets/16316402/6a3b45a7-4475-4d78-a4e7-00d9757124db
### Converted
https://github.com/open-mmlab/Amphion/assets/16316402/76130374-0d56-4682-b6f3-7fefc98ff512

**Comment by ArkhamImp** [comment]
Samples of VitsVC: https://x8gvg3n7v3.feishu.cn/docx/SPbnd0gHcowovGxCyOLcndfanAb?from=from_copylink

**Review by RMSnow — CHANGES_REQUESTED** [review]
Thanks @ArkhamImp ! The VitsVC samples sound better than TransformerVC. You can integrate the both two if you are ready!

**Comment by ArkhamImp** [comment]
Ready to integrate.

**Pull request closed without merging**
