### PR TITLE
Added Diffusion Based Vocoder

### PR DESCRIPTION
**Pull request by VocodexElysium**
1. DiffWave is added.
2. Some code cleaning regarding vocoder inference.
3. Current Vocoder Inference can now support various types of vocoders in a single Inferencor.

### CODE REVIEW

**Review by VocodexElysium — COMMENTED** [review]
Able to merge

**Comment by zhizhengwu** [comment]
Could you please provide some samples? Original vs vocoded

**Review by RMSnow — CHANGES_REQUESTED** [review]
Please add the copyright information into every newly added files.

**Review by VocodexElysium — COMMENTED** [review]
CopyRight added

**Comment by VocodexElysium** [comment]
> Could you please provide some samples? Original vs vocoded

Yes, please wait for a few days

**Comment by VocodexElysium** [comment]
> Please add the copyright information into every newly added files.

Copyright information added

**Comment by VocodexElysium** [comment]
Added DiffWave Pretrained model

**Pull request closed without merging**
