### PR TITLE
support fs2 24k training, aligned mel setting with gan vocoder

### PR DESCRIPTION
**Pull request by qinghua2016**
* fixed fs2 24k training and inference issues, fixed hifigan vocoder training
* aligned mels feature for acoustic model and vocoder, so that people can use the pretrained model. fixed other data preprocess issues.
* fixed librosa usage issues

### CODE REVIEW

**Comment by RMSnow** [comment]
Please use black to format your code

**Comment by lmxue** [comment]
> * fixed fs2 24k training and inference issues, fixed hifigan vocoder training
> * aligned mels feature for acoustic model and vocoder, so that people can use the pretrained model. fixed other data preprocess issues.
> * fixed librosa usage issues

Thanks for your suggestion. We tried to use the pre-trained vocoder for fs2 with the settings of 100-dimensional mel-spectrogram, but achieved poor results compared with the current settings. Therefore, we have decided to retain the current settings for FS2.

**Comment by VocodexElysium** [comment]
> * fixed fs2 24k training and inference issues, fixed hifigan vocoder training
> * aligned mels feature for acoustic model and vocoder, so that people can use the pretrained model. fixed other data preprocess issues.
> * fixed librosa usage issues

Thanks for your suggestion. As @lmxue mentioned, we have tried to align the FS2 with the default setting of the vocoder in the early stage but resulted in poor performance. If you have got good results with the aligned setting, please attach the pretrained model as well as some demos in this PR and we will process your PR then.

**Comment by jiaqili3** [comment]
Hi, thanks for your suggeston. We're closing this issue for the reasons mentioned by @lmxue and @VocodexElysium , where we tried to use the default vocoder but resulted in poor performance. If you have got good results with the aligned setting, you're welcome to reopen the PR. Thanks!

**Pull request closed without merging**
