### PR TITLE
Add VALL-E pre-trained model trained on 6k-hour Librilight

### PR DESCRIPTION
**Pull request by lmxue**
## ✨ Description

Add the [link](https://huggingface.co/amphion/valle_librilight_6k) of the VALL-E pre-trained model trained on a part of Librilight (6k hour). The demo can be found [here](https://huggingface.co/amphion/valle_librilight_6k/tree/main/samples).

## 🚧 Related Issues

None.

## 👨‍💻 Changes Proposed

- [x] Update RREADME.md in egs/tts/VALL-E.

## 🧑‍🤝‍🧑 Who Can Review?

@zhizhengwu @HeCheng0625 @RMSnow 

## 🛠 TODO

- [x] Add processing scripts for Librilight. @HarryHe11 

## ✅ Checklist

- [x]  Code has been reviewed
- [x]  Code complies with the project's code standards and best practices
- [x]  Code has passed all tests
- [x]  Code does not affect the normal use of existing features
- [x]  Code has been commented properly
- [x]  Documentation has been updated (if applicable)
- [x]  Demo/checkpoint has been attached (if applicable)

### CODE REVIEW

**Review by RMSnow — APPROVED** [review]
LGTM. Looking forward to the future huggingface gradio demo!

**Comment by HarryHe11** [comment]
Hi liumeng, I've added processing scripts for Librilight, plz check this pr: https://github.com/open-mmlab/Amphion/pull/107

**Comment by lmxue** [comment]
> Hi liumeng, I've added processing scripts for Librilight, plz check this pr: #107

**Comment by lmxue** [comment]
> Hi liumeng, I've added processing scripts for Librilight, plz check this pr: #107

I have reviewed and left comments on PR #107. Please check it out.

**Comment by HarryHe11** [comment]
> > Hi liumeng, I've added processing scripts for Librilight, plz check this pr: #107
> 
> I have reviewed and left comments on PR #107. Please check it out.

Thank you so much for your effort! I will check it out today.

**Comment by zhizhengwu** [comment]
What's the status of this PR?

**Comment by lmxue** [comment]
> What's the status of this PR?

TODO has been finished and reviewed. So this PR will be merged ASAP.

**Pull request merged**
